version: '3'
services:
  postgres:
    image: postgres:15.2
    ports: 
      - 5432:5432
    env_file:
      - ./docker/envs/database.env

  windguru_mock:
    image: windguru_mock:latest
    build:
      context: ./docker/mocks/
      args:
        MOCK_PATH: windguru
    ports: 
      - 8001:8000

  forecasts_ingester:
    image: forecast_ingester:latest
    build: 
      context: ./services/forecasts_ingester/
      dockerfile: ../../docker/Dockerfile
      args:
        SERVICE_NAME: forecasts_ingester
        BINARY_NAME: forecasts_ingester
        BINARY_PATH: bin/app.rs
    command: 
      - forecasts_ingester
    environment:
      RUSTAPP__WINDGURU__URL: http://localhost:8001
      RUSTAPP__STORAGE__TYPE: postgresql
      RUSTAPP__STORAGE__CONFIG__CONNECTION_URL: postgres://username:password@localhost:5432/windudindu
    volumes:
      - ./services/forecasts_ingester/Settings.toml:/app/Settings.toml
    network_mode: host
    depends_on:
      - postgres
      - forecasts_ingester_migrator

  forecasts_ingester_migrator:
    image: forecast_ingester_migrator:latest
    build: 
      context: ./services/forecasts_ingester/
      dockerfile: ../../docker/Dockerfile
      args:
        SERVICE_NAME: forecasts_ingester
        BINARY_NAME: forecasts_ingester_migrator
        BINARY_PATH: bin/migrator.rs
    command: 
      - forecasts_ingester_migrator
    environment:
      RUSTAPP__STORAGE__TYPE: postgresql
      RUSTAPP__STORAGE__CONFIG__CONNECTION_URL: postgres://username:password@postgres/windudindu

