[windguru]
# url = "https://www.windguru.cz"
url = "http://localhost:8001"
spots = [36048]
models = [3]

[storage]
type = "postgresql"

[storage.config]
connection_url = "postgres://username:password@localhost:5432/windudindu"

